version: 2
updates:
  - package-ecosystem: npm
    directory: /apps/web
    target-branch: test
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    groups:
      frontend-minor-and-patch:
        patterns:
          - "*"
        update-types:
          - minor
          - patch

  - package-ecosystem: pip
    directory: /apps/api
    target-branch: test
    schedule:
      interval: weekly
    open-pull-requests-limit: 5

  - package-ecosystem: github-actions
    directory: /
    target-branch: test
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
