"""초기 스키마

Revision ID: 0e89b871c6a2
Revises: 
Create Date: 2026-08-17 01:03:32.430221

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0e89b871c6a2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('kind', sa.Text(), server_default='agency', nullable=False),
    sa.Column('plan_tier', sa.Enum('per_festival', 'annual', 'enterprise', name='plan_tier'), server_default='per_festival', nullable=False),
    sa.Column('festival_quota', sa.Integer(), nullable=True),
    sa.Column('contact_email', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_organizations'))
    )
    op.create_table('rubric_calibrations',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('rubric_version', sa.Text(), nullable=False),
    sa.Column('sample_size', sa.Integer(), nullable=False),
    sa.Column('method', sa.Text(), nullable=False),
    sa.Column('correlation', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('validated_by', sa.Text(), nullable=False),
    sa.Column('validated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('sample_size > 0', name=op.f('ck_rubric_calibrations_sample_size_positive')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rubric_calibrations')),
    sa.UniqueConstraint('rubric_version', name=op.f('uq_rubric_calibrations_rubric_version'))
    )
    op.create_table('tourism_snapshots',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('region_key', sa.Text(), nullable=False),
    sa.Column('base_month', sa.CHAR(length=6), nullable=False),
    sa.Column('provider', sa.Enum('kto_live', 'demo', name='tourism_provider'), nullable=False),
    sa.Column('stay_index', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('spend_index', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('demand_index', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('season_fit', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('content_count', sa.Integer(), nullable=True),
    sa.Column('estimated_daily_capacity', sa.Integer(), nullable=True),
    sa.Column('congestion_risk', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('local_link_readiness', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('congestion_forecast', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('avg_dwell_minutes', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('hourly_pattern', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('visitor_counts_raw', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('related_spots', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('hub_spots', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('resources', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('source_note', sa.Text(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tourism_snapshots')),
    sa.UniqueConstraint('region_key', 'base_month', 'provider', name='uq_tourism_snapshots_key')
    )
    op.create_index('ix_tourism_snapshots_expiry', 'tourism_snapshots', ['expires_at'], unique=False)
    op.create_table('festivals',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('organization_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('region', sa.Text(), nullable=False),
    sa.Column('venue', sa.Text(), nullable=False),
    sa.Column('starts_on', sa.Date(), nullable=False),
    sa.Column('ends_on', sa.Date(), nullable=False),
    sa.Column('expected_visitors', sa.Integer(), nullable=False),
    sa.Column('total_budget', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.Enum('draft', 'planning', 'ready', 'live', 'closed', name='festival_status'), server_default='planning', nullable=False),
    sa.Column('plan_stage', sa.Enum('draft', 'layout', 'operations', 'proposal', name='plan_stage'), server_default='draft', nullable=False),
    sa.Column('is_demo', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('allow_photo_experience', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('area_code', sa.Text(), nullable=True),
    sa.Column('sigungu_code', sa.Text(), nullable=True),
    sa.Column('legal_dong_code', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('ends_on >= starts_on', name=op.f('ck_festivals_period_valid')),
    sa.CheckConstraint('expected_visitors > 0', name=op.f('ck_festivals_visitors_positive')),
    sa.CheckConstraint('total_budget >= 0', name=op.f('ck_festivals_budget_non_negative')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_festivals_organization_id'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_festivals'))
    )
    op.create_index('ix_festivals_org_recent', 'festivals', ['organization_id', 'created_at', 'id'], unique=False, postgresql_where='archived_at IS NULL')
    op.create_table('booths',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('festival_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('booth_type', sa.Enum('food', 'experience', 'performance', 'information', 'local_shop', 'etc', name='booth_type'), nullable=False),
    sa.Column('type_label', sa.String(length=60), nullable=True),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('manager_name', sa.String(length=120), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('verify_mode', sa.Enum('staff_scan', 'participant_scan', name='booth_verify_mode'), server_default='staff_scan', nullable=False),
    sa.Column('qr_mode', sa.Enum('printed', 'rotating', name='booth_qr_mode'), server_default='printed', nullable=False),
    sa.Column('qr_secret', sa.LargeBinary(), server_default=sa.text('gen_random_bytes(32)'), nullable=False),
    sa.Column('use_experience', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('experience_theme', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['festival_id'], ['festivals.id'], name=op.f('fk_booths_festival_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_booths'))
    )
    op.create_index('ix_booths_festival', 'booths', ['festival_id'], unique=False, postgresql_where='archived_at IS NULL')
    op.create_index('uq_booths_festival_name', 'booths', ['festival_id', sa.literal_column('lower(name)')], unique=True, postgresql_where='archived_at IS NULL')
    op.create_table('festival_plans',
    sa.Column('festival_id', sa.BigInteger(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('purposes', sa.ARRAY(sa.Text()), server_default='{}', nullable=False),
    sa.Column('target_segments', sa.ARRAY(sa.Text()), server_default='{}', nullable=False),
    sa.Column('core_audience', sa.Text(), nullable=True),
    sa.Column('staff_count', sa.Integer(), nullable=True),
    sa.Column('volunteer_count', sa.Integer(), nullable=True),
    sa.Column('safety_staff_count', sa.Integer(), nullable=True),
    sa.Column('parking_capacity', sa.Integer(), nullable=True),
    sa.Column('venue_capacity', sa.Integer(), nullable=True),
    sa.Column('planned_performance', sa.Integer(), server_default='0', nullable=False),
    sa.Column('planned_experience', sa.Integer(), server_default='0', nullable=False),
    sa.Column('planned_food', sa.Integer(), server_default='0', nullable=False),
    sa.Column('planned_local_shop', sa.Integer(), server_default='0', nullable=False),
    sa.Column('planned_tour_info', sa.Integer(), server_default='0', nullable=False),
    sa.Column('planned_etc', sa.Integer(), server_default='0', nullable=False),
    sa.Column('transit_access', sa.Text(), nullable=True),
    sa.Column('traffic_plan', sa.Text(), nullable=True),
    sa.Column('crowd_plan', sa.Text(), nullable=True),
    sa.Column('safety_plan', sa.Text(), nullable=True),
    sa.Column('tourism_link_plan', sa.Text(), nullable=True),
    sa.Column('local_commerce_plan', sa.Text(), nullable=True),
    sa.Column('lodging_plan', sa.Text(), nullable=True),
    sa.Column('promotion_plan', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['festival_id'], ['festivals.id'], name=op.f('fk_festival_plans_festival_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('festival_id', name=op.f('pk_festival_plans'))
    )
    op.create_table('participants',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('festival_id', sa.BigInteger(), nullable=False),
    sa.Column('code', sa.Text(), nullable=False),
    sa.Column('secret_hash', sa.Text(), nullable=False),
    sa.Column('recovery_hash', sa.Text(), nullable=True),
    sa.Column('recovery_attempts', sa.SmallInteger(), server_default='0', nullable=False),
    sa.Column('anonymized_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("code ~ '^FF-[0-9A-Z]{8}$'", name=op.f('ck_participants_code_format')),
    sa.ForeignKeyConstraint(['festival_id'], ['festivals.id'], name=op.f('fk_participants_festival_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_participants')),
    sa.UniqueConstraint('festival_id', 'code', name='uq_participants_festival_code')
    )
    op.create_table('stamp_boards',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('festival_id', sa.BigInteger(), nullable=False),
    sa.Column('version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('rows', sa.SmallInteger(), nullable=False),
    sa.Column('cols', sa.SmallInteger(), nullable=False),
    sa.Column('reveal_mode', sa.Enum('random', 'booth_assigned', name='reveal_mode'), server_default='random', nullable=False),
    sa.Column('grant_unit', sa.Enum('booth', 'mission', name='grant_unit'), server_default='booth', nullable=False),
    sa.Column('image_url', sa.Text(), server_default='/images/chuncheon-stamp-board.png', nullable=False),
    sa.Column('complete_message', sa.Text(), server_default='모든 축제 조각을 완성했습니다!', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('(rows, cols) IN ((2,2),(2,3),(3,3))', name=op.f('ck_stamp_boards_grid_supported')),
    sa.CheckConstraint('cols BETWEEN 2 AND 3', name=op.f('ck_stamp_boards_cols_range')),
    sa.CheckConstraint('rows BETWEEN 2 AND 3', name=op.f('ck_stamp_boards_rows_range')),
    sa.CheckConstraint('version >= 1', name=op.f('ck_stamp_boards_version_positive')),
    sa.ForeignKeyConstraint(['festival_id'], ['festivals.id'], name=op.f('fk_stamp_boards_festival_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_stamp_boards')),
    sa.UniqueConstraint('festival_id', name=op.f('uq_stamp_boards_festival_id'))
    )
    op.create_table('festival_staff',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('festival_id', sa.BigInteger(), nullable=False),
    sa.Column('role', sa.Enum('planner', 'operator', 'booth_manager', name='staff_role'), nullable=False),
    sa.Column('display_name', sa.Text(), nullable=False),
    sa.Column('booth_id', sa.BigInteger(), nullable=True),
    sa.Column('access_code_hash', sa.Text(), nullable=False),
    sa.Column('failed_attempts', sa.Integer(), server_default='0', nullable=False),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("role = 'booth_manager' OR booth_id IS NULL", name=op.f('ck_festival_staff_booth_only_for_booth_manager')),
    sa.ForeignKeyConstraint(['booth_id'], ['booths.id'], name=op.f('fk_festival_staff_booth_id'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['festival_id'], ['festivals.id'], name=op.f('fk_festival_staff_festival_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_festival_staff'))
    )
    op.create_index('ix_festival_staff_festival', 'festival_staff', ['festival_id'], unique=False, postgresql_where='is_active')
    op.create_table('missions',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('festival_id', sa.BigInteger(), nullable=False),
    sa.Column('booth_id', sa.BigInteger(), nullable=True),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('description', sa.String(length=2000), nullable=True),
    sa.Column('points', sa.Integer(), server_default='0', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('experience_type', sa.Enum('stamp', 'quiz', 'photo', 'survey', 'info', name='experience_type'), server_default='stamp', nullable=False),
    sa.Column('experience_config', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('points BETWEEN 0 AND 1000000', name=op.f('ck_missions_points_range')),
    sa.ForeignKeyConstraint(['booth_id'], ['booths.id'], name=op.f('fk_missions_booth_id'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['festival_id'], ['festivals.id'], name=op.f('fk_missions_festival_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_missions'))
    )
    op.create_index('ix_missions_booth', 'missions', ['booth_id'], unique=False, postgresql_where='archived_at IS NULL')
    op.create_index('ix_missions_festival', 'missions', ['festival_id'], unique=False, postgresql_where='archived_at IS NULL')
    op.create_table('stamp_tiles',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('board_id', sa.BigInteger(), nullable=False),
    sa.Column('board_version', sa.Integer(), nullable=False),
    sa.Column('tile_index', sa.SmallInteger(), nullable=False),
    sa.Column('assigned_booth_id', sa.BigInteger(), nullable=True),
    sa.CheckConstraint('tile_index >= 0', name=op.f('ck_stamp_tiles_tile_index_non_negative')),
    sa.ForeignKeyConstraint(['assigned_booth_id'], ['booths.id'], name=op.f('fk_stamp_tiles_assigned_booth_id'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['board_id'], ['stamp_boards.id'], name=op.f('fk_stamp_tiles_board_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_stamp_tiles')),
    sa.UniqueConstraint('board_id', 'board_version', 'tile_index', name='uq_stamp_tiles_index')
    )
    op.create_index('uq_stamp_tiles_booth', 'stamp_tiles', ['board_id', 'board_version', 'assigned_booth_id'], unique=True, postgresql_where='assigned_booth_id IS NOT NULL')
    op.create_table('diagnoses',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('festival_id', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'running', 'completed', 'failed', name='diagnosis_status'), server_default='pending', nullable=False),
    sa.Column('rubric_version', sa.Text(), server_default='v1', nullable=False),
    sa.Column('total_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('risk', sa.Enum('stable', 'caution', 'risk', name='risk_level'), nullable=True),
    sa.Column('input_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('tourism_snapshot_id', sa.BigInteger(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('requested_by_staff_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('total_score IS NULL OR total_score BETWEEN 0 AND 100', name=op.f('ck_diagnoses_score_range')),
    sa.ForeignKeyConstraint(['festival_id'], ['festivals.id'], name=op.f('fk_diagnoses_festival_id'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['requested_by_staff_id'], ['festival_staff.id'], name=op.f('fk_diagnoses_requested_by_staff_id'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tourism_snapshot_id'], ['tourism_snapshots.id'], name=op.f('fk_diagnoses_tourism_snapshot_id'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_diagnoses'))
    )
    op.create_index('ix_diagnoses_latest', 'diagnoses', ['festival_id', 'created_at'], unique=False)
    op.create_table('recommendation_feedbacks',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('festival_id', sa.BigInteger(), nullable=False),
    sa.Column('booth_id', sa.BigInteger(), nullable=True),
    sa.Column('rec_type', sa.Enum('REDISTRIBUTE', 'NO_ACTIVITY', name='recommendation_type'), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('verdict', sa.Boolean(), nullable=False),
    sa.Column('staff_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['booth_id'], ['booths.id'], name=op.f('fk_recommendation_feedbacks_booth_id'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['festival_id'], ['festivals.id'], name=op.f('fk_recommendation_feedbacks_festival_id'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['staff_id'], ['festival_staff.id'], name=op.f('fk_recommendation_feedbacks_staff_id'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_recommendation_feedbacks'))
    )
    op.create_index('ix_recommendation_feedbacks_festival', 'recommendation_feedbacks', ['festival_id', 'rec_type'], unique=False)
    op.create_table('reward_campaigns',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('festival_id', sa.BigInteger(), nullable=False),
    sa.Column('booth_id', sa.BigInteger(), nullable=False),
    sa.Column('mission_id', sa.BigInteger(), nullable=True),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('message', sa.String(length=500), nullable=False),
    sa.Column('bonus_points', sa.Integer(), nullable=False),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_by_staff_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('bonus_points >= 0', name=op.f('ck_reward_campaigns_bonus_non_negative')),
    sa.CheckConstraint('ends_at > starts_at', name=op.f('ck_reward_campaigns_window_valid')),
    sa.ForeignKeyConstraint(['booth_id'], ['booths.id'], name=op.f('fk_reward_campaigns_booth_id'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by_staff_id'], ['festival_staff.id'], name=op.f('fk_reward_campaigns_created_by_staff_id'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['festival_id'], ['festivals.id'], name=op.f('fk_reward_campaigns_festival_id'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['mission_id'], ['missions.id'], name=op.f('fk_reward_campaigns_mission_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reward_campaigns'))
    )
    op.create_index('ix_reward_campaigns_active', 'reward_campaigns', ['festival_id', 'starts_at', 'ends_at'], unique=False, postgresql_where='is_active')
    op.create_table('visitor_counts',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('festival_id', sa.BigInteger(), nullable=False),
    sa.Column('count_date', sa.Date(), nullable=False),
    sa.Column('visitors', sa.Integer(), nullable=False),
    sa.Column('source', sa.Enum('beacon', 'manual_counter', 'kto_bigdata', 'partner', 'estimate', name='visitor_source'), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('recorded_by_staff_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('visitors >= 0', name=op.f('ck_visitor_counts_visitors_non_negative')),
    sa.ForeignKeyConstraint(['festival_id'], ['festivals.id'], name=op.f('fk_visitor_counts_festival_id'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recorded_by_staff_id'], ['festival_staff.id'], name=op.f('fk_visitor_counts_recorded_by_staff_id'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_visitor_counts')),
    sa.UniqueConstraint('festival_id', 'count_date', 'source', name='uq_visitor_counts_key')
    )
    op.create_table('diagnosis_items',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('diagnosis_id', sa.BigInteger(), nullable=False),
    sa.Column('category', sa.Enum('tourism_demand', 'crowd_safety', 'program_balance', 'local_linkage', 'ops_readiness', name='diagnosis_category'), nullable=False),
    sa.Column('score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('max_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('level', sa.Enum('stable', 'caution', 'risk', name='risk_level'), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('recommendation', sa.Text(), nullable=False),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.CheckConstraint('max_score > 0', name=op.f('ck_diagnosis_items_max_score_positive')),
    sa.CheckConstraint('score <= max_score', name=op.f('ck_diagnosis_items_score_within_max')),
    sa.CheckConstraint('score >= 0', name=op.f('ck_diagnosis_items_score_non_negative')),
    sa.ForeignKeyConstraint(['diagnosis_id'], ['diagnoses.id'], name=op.f('fk_diagnosis_items_diagnosis_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_diagnosis_items')),
    sa.UniqueConstraint('diagnosis_id', 'category', name='uq_diagnosis_items_category')
    )
    op.create_table('participations',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('festival_id', sa.BigInteger(), nullable=False),
    sa.Column('participant_id', sa.BigInteger(), nullable=False),
    sa.Column('mission_id', sa.BigInteger(), nullable=True),
    sa.Column('booth_id', sa.BigInteger(), nullable=True),
    sa.Column('status', sa.Enum('issued', 'completed', name='participation_status'), server_default='completed', nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('base_points', sa.Integer(), server_default='0', nullable=False),
    sa.Column('bonus_points', sa.Integer(), server_default='0', nullable=False),
    sa.Column('granted_points', sa.Integer(), sa.Computed('base_points + bonus_points', persisted=True), nullable=False),
    sa.Column('reward_campaign_id', sa.BigInteger(), nullable=True),
    sa.Column('verified_via', sa.Enum('staff_scan', 'participant_scan', name='booth_verify_mode'), nullable=True),
    sa.Column('granted_by_staff_id', sa.BigInteger(), nullable=True),
    sa.Column('response', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('attempt_count', sa.SmallInteger(), server_default='1', nullable=False),
    sa.Column('client_request_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('queued_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(status = 'completed') = (completed_at IS NOT NULL)", name=op.f('ck_participations_completed_consistent')),
    sa.CheckConstraint('attempt_count >= 1', name=op.f('ck_participations_attempt_count_positive')),
    sa.CheckConstraint('base_points >= 0', name=op.f('ck_participations_base_points_non_negative')),
    sa.CheckConstraint('bonus_points >= 0', name=op.f('ck_participations_bonus_points_non_negative')),
    sa.ForeignKeyConstraint(['booth_id'], ['booths.id'], name=op.f('fk_participations_booth_id'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['festival_id'], ['festivals.id'], name=op.f('fk_participations_festival_id'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['granted_by_staff_id'], ['festival_staff.id'], name=op.f('fk_participations_granted_by_staff_id'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['mission_id'], ['missions.id'], name=op.f('fk_participations_mission_id'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['participant_id'], ['participants.id'], name=op.f('fk_participations_participant_id'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reward_campaign_id'], ['reward_campaigns.id'], name=op.f('fk_participations_reward_campaign_id'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_participations'))
    )
    op.create_index('ix_participations_booth_time', 'participations', ['booth_id', 'completed_at'], unique=False, postgresql_where="status = 'completed'")
    op.create_index('ix_participations_festival_time', 'participations', ['festival_id', 'completed_at'], unique=False, postgresql_where="status = 'completed'")
    op.create_index('ix_participations_participant', 'participations', ['participant_id'], unique=False)
    op.create_index('uq_participations_client_request', 'participations', ['client_request_id'], unique=True, postgresql_where='client_request_id IS NOT NULL')
    op.create_index('uq_participations_grant', 'participations', ['participant_id', 'mission_id'], unique=True, postgresql_where='mission_id IS NOT NULL')
    op.create_table('booth_scan_uses',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('booth_id', sa.BigInteger(), nullable=False),
    sa.Column('window_index', sa.BigInteger(), nullable=False),
    sa.Column('participant_id', sa.BigInteger(), nullable=False),
    sa.Column('participation_id', sa.BigInteger(), nullable=True),
    sa.Column('used_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['booth_id'], ['booths.id'], name=op.f('fk_booth_scan_uses_booth_id'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['participant_id'], ['participants.id'], name=op.f('fk_booth_scan_uses_participant_id'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['participation_id'], ['participations.id'], name=op.f('fk_booth_scan_uses_participation_id'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_booth_scan_uses')),
    sa.UniqueConstraint('booth_id', 'window_index', 'participant_id', name='uq_booth_scan_uses_window')
    )
    op.create_index('ix_booth_scan_uses_cleanup', 'booth_scan_uses', ['used_at'], unique=False)
    op.create_table('stamp_reveals',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('board_id', sa.BigInteger(), nullable=False),
    sa.Column('board_version', sa.Integer(), nullable=False),
    sa.Column('participant_id', sa.BigInteger(), nullable=False),
    sa.Column('tile_id', sa.BigInteger(), nullable=False),
    sa.Column('booth_id', sa.BigInteger(), nullable=True),
    sa.Column('participation_id', sa.BigInteger(), nullable=True),
    sa.Column('revealed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['board_id'], ['stamp_boards.id'], name=op.f('fk_stamp_reveals_board_id'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['booth_id'], ['booths.id'], name=op.f('fk_stamp_reveals_booth_id'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['participant_id'], ['participants.id'], name=op.f('fk_stamp_reveals_participant_id'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['participation_id'], ['participations.id'], name=op.f('fk_stamp_reveals_participation_id'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tile_id'], ['stamp_tiles.id'], name=op.f('fk_stamp_reveals_tile_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_stamp_reveals')),
    sa.UniqueConstraint('board_version', 'participant_id', 'tile_id', name='uq_stamp_reveals_tile')
    )
    op.create_index('ix_stamp_reveals_lookup', 'stamp_reveals', ['board_id', 'board_version', 'participant_id'], unique=False)
    op.create_index('uq_stamp_reveals_booth', 'stamp_reveals', ['board_id', 'board_version', 'participant_id', 'booth_id'], unique=True, postgresql_where='booth_id IS NOT NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_stamp_reveals_booth', table_name='stamp_reveals', postgresql_where='booth_id IS NOT NULL')
    op.drop_index('ix_stamp_reveals_lookup', table_name='stamp_reveals')
    op.drop_table('stamp_reveals')
    op.drop_index('ix_booth_scan_uses_cleanup', table_name='booth_scan_uses')
    op.drop_table('booth_scan_uses')
    op.drop_index('uq_participations_grant', table_name='participations', postgresql_where='mission_id IS NOT NULL')
    op.drop_index('uq_participations_client_request', table_name='participations', postgresql_where='client_request_id IS NOT NULL')
    op.drop_index('ix_participations_participant', table_name='participations')
    op.drop_index('ix_participations_festival_time', table_name='participations', postgresql_where="status = 'completed'")
    op.drop_index('ix_participations_booth_time', table_name='participations', postgresql_where="status = 'completed'")
    op.drop_table('participations')
    op.drop_table('diagnosis_items')
    op.drop_table('visitor_counts')
    op.drop_index('ix_reward_campaigns_active', table_name='reward_campaigns', postgresql_where='is_active')
    op.drop_table('reward_campaigns')
    op.drop_index('ix_recommendation_feedbacks_festival', table_name='recommendation_feedbacks')
    op.drop_table('recommendation_feedbacks')
    op.drop_index('ix_diagnoses_latest', table_name='diagnoses')
    op.drop_table('diagnoses')
    op.drop_index('uq_stamp_tiles_booth', table_name='stamp_tiles', postgresql_where='assigned_booth_id IS NOT NULL')
    op.drop_table('stamp_tiles')
    op.drop_index('ix_missions_festival', table_name='missions', postgresql_where='archived_at IS NULL')
    op.drop_index('ix_missions_booth', table_name='missions', postgresql_where='archived_at IS NULL')
    op.drop_table('missions')
    op.drop_index('ix_festival_staff_festival', table_name='festival_staff', postgresql_where='is_active')
    op.drop_table('festival_staff')
    op.drop_table('stamp_boards')
    op.drop_table('participants')
    op.drop_table('festival_plans')
    op.drop_index('uq_booths_festival_name', table_name='booths', postgresql_where='archived_at IS NULL')
    op.drop_index('ix_booths_festival', table_name='booths', postgresql_where='archived_at IS NULL')
    op.drop_table('booths')
    op.drop_index('ix_festivals_org_recent', table_name='festivals', postgresql_where='archived_at IS NULL')
    op.drop_table('festivals')
    op.drop_index('ix_tourism_snapshots_expiry', table_name='tourism_snapshots')
    op.drop_table('tourism_snapshots')
    op.drop_table('rubric_calibrations')
    op.drop_table('organizations')
    # ### end Alembic commands ###

    # ── enum 타입 정리 ─────────────────────────────────────────────────────
    # Alembic autogenerate 는 downgrade 에 DROP TYPE 을 넣어주지 않는다.
    # 타입이 남으면 재-upgrade 시 "type already exists" 로 실패한다.
    for _enum in (
        "recommendation_type",
        "visitor_source",
        "tourism_provider",
        "risk_level",
        "diagnosis_category",
        "diagnosis_status",
        "grant_unit",
        "reveal_mode",
        "participation_status",
        "experience_type",
        "booth_qr_mode",
        "booth_verify_mode",
        "booth_type",
        "staff_role",
        "plan_stage",
        "festival_status",
        "plan_tier",
    ):
        op.execute(f'DROP TYPE IF EXISTS {_enum}')
